#server:
#  port: 7000
#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.218.2:3306/eservicemall_sms
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: eservice-coupon
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.218.2:8848
##        username: nacos
##        password: nacos
#      server-addr: 192.168.218.2:8848
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/coupon/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#
spring:
  main:
    allow-circular-references: true  #允许循环引用
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


