server:
  port: 30000
management:
  zipkin:
    tracing:
      endpoint: http://192.168.218.2:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*" # 暴露所有端点
