#server:
#  port: 11000
#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.56.10:3306/eservice_wms
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: eservice-ware
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.56.10:8848
#mybatis-plus:
#  mapper-locations: classpath:/mapper/ware/*.xml
#  global-config:
#    db-config:
#      id-type: auto
spring:
  main:
    allow-circular-references: true  #允许循环引用
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: 192.168.218.2
    port: 5672
    # 虚拟主机
    virtual-host: /
    # 开启发送端发送确认，无论是否到达broker都会触发回调【发送端确认机制+本地事务表】
    publisher-confirm-type: correlated
    # 开启发送端抵达队列确认，消息未被队列接收时触发回调【发送端确认机制+本地事务表】
    publisher-returns: true
    # 消息在没有被队列接收时是否强行退回
    template:
      mandatory: true
    # 消费者手动确认模式，关闭自动确认，否则会消息丢失
    listener:
      simple:
        acknowledge-mode: manual

management:
  zipkin:
    tracing:
      endpoint: http://192.168.218.2:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*" # 暴露所有端点