server:
  port: 11000
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/eservice_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: eservice-ware
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848
mybatis-plus:
  mapper-locations: classpath:/mapper/ware/*.xml
  global-config:
    db-config:
      id-type: auto


