#server:
#  port: 9000
#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.218.2:3306/eservice_oms
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: eservice-order
#  cloud:
#    nacos:
#      discovery:
#        ##server-addr: 192.168.218.2:8848
#        server-addr: localhost:8848
#mybatis-plus:
#  mapper-locations: classpath:/mapper/order/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#
#
