#server:
#  port: 10000
#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.56.10:3306/eservice_pms
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: eservice-product
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.56.10:8848
#mybatis-plus:
#  mapper-locations: classpath:/mapper/product/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#
#
spring:
  main:
    allow-circular-references: true  #允许循环引用
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false    ## 关闭缓存
  data:
    redis:
      host: 192.168.218.2
      port: 6379

management:
  zipkin:
    tracing:
      endpoint: http://192.168.218.2:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*" # 暴露所有端点
#### 线程池配置
eservicemall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10