#server:
#  port: 8000
#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.218.2:3306/eservice_ums
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: eservice-member
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.218.2:8848
##        username: nacos
##        password: nacos
#      server-addr: 192.168.56.10:8848
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/member/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#

spring:
  session:
    storage-type: redis
  data:
    redis:
      host: 192.168.218.2
      port: 6379
management:
  zipkin:
    tracing:
      endpoint: http://192.168.218.2:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*" # 暴露所有端点