server:
  port: 30010

spring:
  application:
    name: eservice-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  data:
    redis:
      port: 6379
      host: 192.168.218.2
management:
  zipkin:
    tracing:
      endpoint: http://192.168.218.2:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*" # 暴露所有端点

eservicemall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10