server:
  port: 20000
spring:
  application:
    name: eservicemall-auth-server
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  data:
    redis:
      host: 192.168.218.2
      port: 6379
  thymeleaf:
    cache: false

